### ISSUE TITLE
Publish sprs_suitespare_ldl and sprs_suitesparse_camd to crates.io

### ISSUE THREAD

**Issue by michael-p** [vbarrielle/sprs#293]
Hi there,

it looks like the above mentioned sub-crates are not published to crates.io in their most recent versions (and maybe other crates besides the main `sprs` one as well?). This makes updating `sprs` to version 0.11.0 impossible for me because I also need the suitesparse-crates which in the currently published versions still depend on `sprs` 0.10.0.
Everything seems to be updated here on Github however, so probably just needs to be published :)

Thanks a lot for all your work on these crates!
Michael

**Comment by michael-p** [comment]
Is there any chance of getting these crates published somehow? Are there any maintainers left for with publish rights to crates.io? (pinging @mulimoen and @vbarrielle - sorry for bothering you so directly!!)
Thank you very much to everyone involved!

**Comment by StefanUlbrich** [comment]
Not the most elegant solution but this worked for me as a temporary workaround:

```toml
sprs =  {version = "0.11.0", git = "https://github.com/vbarrielle/sprs", rev = "3895313" }
sprs-ldl = {version = "0.10.0", git = "https://github.com/vbarrielle/sprs", rev = "3895313" }
```
